# Generated by Django 5.2.17 on 2026-09-04 17:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaybackToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("ip_prefix", models.CharField(max_length=64)),
                ("device_fingerprint", models.CharField(blank=True, max_length=255)),
                ("consumed", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_tokens",
                        to="catalog.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="playbacktoken",
            index=models.Index(
                fields=["user", "consumed", "expires_at"],
                name="media_playb_user_id_376b6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playbacktoken",
            index=models.Index(
                fields=["user", "issued_at"],
                name="media_playb_user_id_47f038_idx",
            ),
        ),
    ]
