# Generated by Django 5.2.17 on 2026-09-04 15:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_key', models.CharField(max_length=128, unique=True)),
                ('content_type', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('amount_declared', models.PositiveIntegerField(help_text='Montant versé, en dinars.')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Déposée'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée')], default='SUBMITTED', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('purge_after', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='catalog.course'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='inscription_unique_par_user_et_cours'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='enrollment.enrollment'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_examinees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(fields=['status', '-created_at'], name='enrollment__status_48ef34_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(fields=['purge_after'], name='enrollment__purge_a_df11d3_idx'),
        ),
    ]
