# Generated by Django 5.2.17 on 2026-09-04 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROOF_SUBMITTED', 'Preuve de paiement déposée'), ('PROOF_VIEWED', 'Preuve de paiement consultée'), ('PROOF_PURGED', 'Preuve de paiement purgée'), ('ENROLLMENT_ACCEPTED', 'Inscription validée'), ('ENROLLMENT_REJECTED', 'Preuve refusée')], max_length=32)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_auditees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx')],
            },
        ),
    ]
