# Generated by Django 5.2.17 on 2026-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("PROOF_SUBMITTED", "Preuve de paiement déposée"),
                    ("PROOF_VIEWED", "Preuve de paiement consultée"),
                    ("PROOF_PURGED", "Preuve de paiement purgée"),
                    ("ENROLLMENT_ACCEPTED", "Inscription validée"),
                    ("ENROLLMENT_REJECTED", "Preuve refusée"),
                    ("PLAYBACK_ISSUED", "Jeton de lecture émis"),
                    ("PLAYBACK_FLAGGED", "Compte signalé (partage vidéo)"),
                ],
                max_length=32,
            ),
        ),
    ]
