# Generated by Django 5.2.17 on 2026-09-05 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submitted_at__isnull", True)),
                fields=("user", "quiz"),
                name="attempt_une_seule_ouverte_par_utilisateur_quiz",
            ),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)),
                fields=("question",),
                name="choice_une_seule_bonne_reponse_par_question",
            ),
        ),
    ]
