# Generated by Django 5.2.17 on 2026-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="concurrent_play_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
